version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=workpal
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"